name: Attach VisualText Files Assets

on:
  push:
    branches:
      - master

jobs:    
  zip_files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: analyzers/ data/ visualtext/
          recursive: false
          dest: visualtext.zip
          
      - uses: actions/upload-artifact@v1
        with:
          path: ${{ github.workspace }}/visualtext.zip