name: MaxOS

on:
  push:
    branches:
      - master
  
jobs:
  build_engine:
    name: Build NLP-ENGINE
    runs-on: macOS-12

    env:
      VCPKG_DEFAULT_TRIPLET: x64-osx

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Vcpkg bootstrap Shell
        run: ./bootstrap-vcpkg.sh
        shell: bash
        working-directory: vcpkg
        
      - name: Install autoconf-archive
        run: brew install autoconf-archive

      - name: Install Brew
        run: brew install automake

      - name: Install ICU
        run: vcpkg install
        working-directory: vcpkg

      - name: Make build directory
        run: mkdir build

      - name: Generate Solution MacOs
        run: cmake -DCMAKE_BUILD_TYPE=Release -DVCPKG_BUILD_TYPE=release -DCMAKE_PREFIX_PATH=/usr/local/opt/icu4c -B build -S . -DCMAKE_CXX_FLAGS=-std=c++11

      - name: Cmake Build all targets MaxOs
        run: cmake --build build/ --target all

      - name: Test executable --version
        run: ./bin/nlp.exe --version || true
        
      - name: List $RUNNER_WORKSPACE after build
        run: find $RUNNER_WORKSPACE
        shell: bash

      - name: Rename nlp.exe to nlpm.exe
        run: mv bin/nlp.exe bin/nlpm.exe
        shell: bash

      - name: Rename libicutu.a to libicutum.a
        run: cp vcpkg/buildtrees/icu/x64-osx-rel/lib/libicutu.a vcpkg/buildtrees/icu/x64-osx-rel/lib/libicutum.a
        shell: bash

      - name: Rename libicuuc.a to libicuucm.a
        run: cp vcpkg/buildtrees/icu/x64-osx-rel/lib/libicuuc.a vcpkg/buildtrees/icu/x64-osx-rel/lib/libicuucm.a
        shell: bash

      - name: Upload nlpm.exe
        uses: actions/upload-artifact@v3
        with:
          path: bin/nlpm.exe
          
      - name: Upload libicutu.a
        uses: actions/upload-artifact@v3
        with:
          path: vcpkg/buildtrees/icu/x64-osx-rel/lib/libicutum.a

      - name: Upload libicuuc.a
        uses: actions/upload-artifact@v3
        with:
          path: vcpkg/buildtrees/icu/x64-osx-rel/lib/libicuucm.a
