name: Attach Engine File Assets

on:
  push:
    branches: [master]
  pull_request:
    types: [opened]

jobs:    
  zip-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - run: git submodule update --init --recursive
      - uses: papeloto/action-zip@v1
        with:
          files: analyzers/ data/
          recursive: false
          dest: nlpengine.zip
          
      - uses: actions/upload-artifact@v1
        with:
          name: nlpengine
          path: ${{ github.workspace }}/nlpengine.zip
