name: Linux

push:
  branches:
    - main
      
jobs:
  build_engine:
    name: Build NLP-ENGINE
    runs-on: ubuntu-latest

    env:
      VCPKG_DEFAULT_TRIPLET: x64-linux

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Vcpkg Bootstrap Shell
        run: ./bootstrap-vcpkg.sh
        shell: bash
        working-directory: vcpkg

      - name: Install autoconf-archive
        run: sudo apt-get install -y autoconf-archive

      - name: Install ICU
        run: vcpkg install
        working-directory: vcpkg

      - name: Make build directory
        run: mkdir build

      - name: Generate Solution Linux
        run: cmake -DCMAKE_BUILD_TYPE=Release -DVCPKG_BUILD_TYPE=release -B build -S .

      - name: List $RUNNER_WORKSPACE after build
        run: find $RUNNER_WORKSPACE
        shell: bash

      - name: Cmake Build all targets Linux
        run: cmake --build build/ --target all

      - name: Test executable --version
        run: ./bin/nlp.exe --version || true

      - uses: actions/upload-artifact@v3
        with:
          name: nlpl.exe
          path: bin/nlp.exe

      - uses: actions/upload-artifact@v3
        with:
          path: vcpkg_installed/x64-linux/lib/libicutu.a

      - uses: actions/upload-artifact@v3
        with:
          path: vcpkg_installed/x64-linux/lib/libicuuc.a
