name: Build

on: push
# on:
#   push:
#     branches: [master]
#   pull_request:
#     types: [opened, synchronize, reopened]

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [macos-latest, ubuntu-latest, windows-latest]
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v2
      # build project
      - name: make build directory
        run: mkdir build
      - name: Cmake Build
        run: cmake -Bbuild -H.
      - name: Cmake Make
        run: cmake --build build/ --target all
