name: Attach Released Assets

on:
  release:
    types:
      - created
      
jobs:    
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make build directory
        run: mkdir build
      - name: Cmake Configure
        run: cmake -DCMAKE_BUILD_TYPE=Release -Bbuild -S.

      - name: Cmake Build all targets on Linux
        run: cmake --build build/ --target all
        
      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: "./bin/nlp.exe"
          asset_name: "nlpl.exe"