
name: Linux Create Released Asset

on:
  release:
    types:
      - created
      
jobs:
  job:
    name: Linux Create NLP-ENGINE
    runs-on: ubuntu-latest

    env:
      VCPKG_DEFAULT_TRIPLET: x64-linux

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Vcpkg bootstrap Shell
        run: ./bootstrap-vcpkg.sh
        shell: bash
        working-directory: vcpkg

      - name: Install ICU
        run: vcpkg install
        working-directory: vcpkg
        
      - name: List $RUNNER_WORKSPACE before build
        run: find $RUNNER_WORKSPACE
        shell: bash

      - name: Make build directory
        run: mkdir build

      - name: Generate Solution Linux
        run: cmake -DCMAKE_BUILD_TYPE=Release -DVCPKG_BUILD_TYPE=release -B build -S .

      - name: Cmake Build all targets Linux
        run: cmake --build build/ --target all

      - name: Zip nlp and icu files
        uses: papeloto/action-zip@v1
        with:
          files: ./bin/nlp.exe ./vcpkg_installed/x64-linux/lib/libicutu.a ./vcpkg_installed/x64-linux/lib/libicuuc.a
          recursive: false
          dest: nlpl.zip

      - name: Upload zip artifact
        uses: actions/upload-artifact@v1
        with:
          name: nlpl
          path: ${{ github.workspace }}/nlpl.zip
        
      - name: Attach Zip to Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: nlpl.zip
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
