name: Build Linux

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  Build:
    runs-on: linux-latest
    steps:
      - uses: actions/checkout@v2
      # build project
      - name: make build directory
        run: mkdir build
      - name: Cmake Configure
        run: cmake -Bbuild -S.
      - name: Cmake Build all targets on Windows
        run: cmake --build build/ --target all

      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: "./nlp-engine.linux.exe"
