
name: MacOS Create Released Asset

on:
  release:
    types:
      - created
      
jobs:
  build_executable:
    name: MacOS Create NLP-ENGINE
    runs-on: macos-latest

    env:
      VCPKG_DEFAULT_TRIPLET: x64-osx

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Vcpkg bootstrap Shell
        run: ./bootstrap-vcpkg.sh
        shell: bash
        working-directory: vcpkg

      - name: Mac Install Brew
        run: brew install automake

      - name: Install ICU
        run: vcpkg install
        working-directory: vcpkg

      - name: Make build directory
        run: mkdir build

      - name: Generate Solution MacOs
        run: cmake -DCMAKE_BUILD_TYPE=Release -DVCPKG_BUILD_TYPE=release -DCMAKE_PREFIX_PATH=/usr/local/opt/icu4c -B build -S . -DCMAKE_CXX_FLAGS=-std=c++11

      - name: Cmake Build all targets Linux
        run: cmake --build build/ --target all

      - name: List $RUNNER_WORKSPACE before build
        run: find $RUNNER_WORKSPACE
        shell: bash
                
      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: "./bin/nlp.exe"
          asset_name: "nlpm.exe"

      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: "./vcpkg/buildtrees/icu/x64-osx-rel/lib/libicutu.a"
          asset_name: "libicutum.a"

      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: "./vcpkg/buildtrees/icu/x64-osx-rel/lib/libicuuc.a"
          asset_name: "libicuucm.a"
