name: Attach Engine File Assets

on:
  push:
    tags:
    - '*'

jobs:    
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: git submodule update --init --recursive
      - uses: papeloto/action-zip@v1
        with:
          files: analyzers/ data/
          recursive: false
          dest: nlpengine.zip
          
      - uses: actions/upload-artifact@v1
        with:
          name: nlpengine
          path: ${{ github.workspace }}/nlpengine.zip
          
      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: nlpengine.zip
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
