name: Attach Released Assets

on:
  release:
    types:
      - created
      
jobs:    
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: make build directory
        run: mkdir build
      - name: Cmake Configure
        run: cmake -Bbuild -S.
        
      - name: Cmake Build all targets on Windows
        run: cmake --build build/ --target ALL_BUILD
        if: ${{ matrix.os == 'windows-latest' }}
      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: "./bin/nlp.exe"

      - name: Cmake Build all targets on Linux
        run: cmake --build build/ --target all
        if: ${{ matrix.os == 'ubuntu-latest' }}
      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: "./bin/nlp"

      - name: Cmake Build all targets on Unix
        run: cmake --build build/ --target all
        if: ${{ matrix.os == 'macos-latest' }}
      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: "./bin/nlp"
