name: Test Linux

on:
  push
      
jobs:
  job:
    name: Linux Compile Test
    runs-on: ubuntu-latest

    env:
      VCPKG_DEFAULT_TRIPLET: x64-linux

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Vcpkg bootstrap Shell
        run: ./bootstrap-vcpkg.sh
        shell: bash
        working-directory: vcpkg

      - name: Install ICU
        run: vcpkg install
        working-directory: vcpkg

      - name: Make build directory
        run: mkdir build

      - name: Generate Solution Linux
        run: cmake -DCMAKE_BUILD_TYPE=Release -B build -S .

      - name: Cmake Build all targets Linux
        run: cmake --build build/ --target all