
name: Test Windows

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  job:
    name: Windows Compile Test
    runs-on: windows-2019

    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Vcpkg bootstrap Windows
        run: bootstrap-vcpkg.bat
        working-directory: vcpkg

      - name: Install ICU
        run: vcpkg install
        working-directory: vcpkg

      - name: Make build directory
        run: mkdir build

      - name: Generate Solution Windows
        run: cmake -B build -A Win32 -DCMAKE_TOOLCHAIN_FILE='${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake'

      - name: Cmake Build all targets Windows
        run: cmake --build build --config Release --target nlp

      - uses: actions/upload-artifact@v3
        with:
          name: nlp.exe
          path: bin/Release
          
      - uses: actions/upload-artifact@v3
        with:
          name: icudt69.dll
          path: vcpkg/buildtrees/icu/x64-windows-rel/lib/icudt69.dll

      - uses: actions/upload-artifact@v3
        with:
          name: icuuc69.dll
          path: vcpkg/buildtrees/icu/x64-windows-rel/lib/icuuc69.dll