name: Attach Released Assets

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
      
jobs:    
  build:
    runs-on: ubuntu-latest
    with:
      submodules: true
      
    env:
      VCPKG_DEFAULT_TRIPLET: x64-linux

    steps:
      - uses: actions/checkout@v2
      - name: make build directory
        run: mkdir build
        
      - name: Run vcpkg
        uses: lukka/run-vcpkg@v10.1
        with:
          vcpkgArguments: 'icu'

      - name: Cmake Configure
        run: cmake .. -G "Visual Studio 16 2019" -A Win32 -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake
        run: cmake -DCMAKE_BUILD_TYPE=Release -Bbuild -S.

      - name: Cmake Build
        run: cmake --build . --config Release -- -m
