name: Test Linux

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]
      
jobs:
  job:
    name: Linux Compile Test
    runs-on: ubuntu-latest

    env:
      VCPKG_DEFAULT_TRIPLET: x64-linux

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Vcpkg Bootstrap Shell
        run: ./bootstrap-vcpkg.sh
        shell: bash
        working-directory: vcpkg

      - name: Install autoconf-archive
        run: sudo apt-get install -y autoconf-archive

      - name: Install ICU
        run: vcpkg install
        working-directory: vcpkg

      - name: Make build directory
        run: mkdir build

      - name: Generate Solution Linux
        run: cmake -DCMAKE_BUILD_TYPE=Release -DVCPKG_BUILD_TYPE=release -B build -S .

      - name: List $RUNNER_WORKSPACE before build
        run: find $RUNNER_WORKSPACE
        shell: bash

      - name: Cmake Build all targets Linux
        run: cmake --build build/ --target all

      - name: Test executable --version
        run: ./bin/nlp.exe --version || true

      - uses: actions/upload-artifact@v3
        with:
          name: nlp.exe
          path: bin

      - uses: actions/upload-artifact@v3
        with:
          name: ibicutu.a
          path: vcpkg_installed/x64-linux/lib/libicutu.a

      - uses: actions/upload-artifact@v3
        with:
          name: libicuuc.a
          path: vcpkg_installed/x64-linux/lib/libicuuc.a
