name: Attach Released Assets

on: [push]

jobs:    
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: analyzers/ data/ visualtext/
          dest: visualtext.zip
          
      - uses: actions/upload-artifact@v1
        id: vt-zip
        with:
          name: my-artifact
          path: ${{ github.workspace }}/result.zip
          
      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ steps.vt-zip.upload_url }}
          asset_path: "./visualtext.zip"
