name: Attach Released Assets

on: [push]

jobs:    
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        id: vt-zip
        with:
          files: analyzers/ data/ visualtext/
          dest: visualtext.zip
          
      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ steps.vt-zip.outputs.vt-zip }}
          asset_path: "./visualtext.zip"
