name: Attach Released Assets

on:
  release:
    types:
      - created
      
jobs:    
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: analyzers/ data/ visualtext/
          dest: visualtext.zip
          
      - uses: actions/upload-artifact@v1
        with:
          name: visualtext-files
          path: ${{ github.workspace }}/visualtext.zip
