
name: Attach Released Assets

on:
  release:
    types:
      - created
      
jobs:    
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: make build directory
        run: mkdir build
      - name: Cmake Configure
        run: cmake -Bbuild -S.

      - name: Cmake Build all targets on Windows
        run: cmake --build build --target ALL_BUILD
        
      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: "./bin/Debug/nlp.exe"
          asset_name: "nlpw.exe"
